openapi: "3.0.3"
info:
  title: "kotlin_playground API"
  description: "kotlin_playground API"
  version: "1.0.0"
servers:
- url: "https://kotlin_playground"
paths:
  /api/books:
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/CreateBookRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CreateBookResponse"
components:
  schemas:
    CreateBookRequest:
      type: "object"
      properties:
        title:
          type: "string"
        isbn:
          type: "string"
    CreateBookResponse:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        title:
          type: "string"
        isbn:
          type: "string"